### ISSUE TITLE
Impostor v0.9.9.4 test prior to release 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyImpostors-Feedback#41]
Test impostors in build prior to release 0.9.9.4

User reported issue with blurry results. 

-- Test scene Impostorcolored barrels 
-- URP 2022.3.20 
-- Build **3d webgl** 

![image](https://github.com/AmplifyCreations/AmplifyImpostors-Feedback/assets/47288655/2855dc6b-96fc-4e1c-a907-32e9b1c5db80)

Note textures prior to build are reported ok 
![image](https://github.com/AmplifyCreations/AmplifyImpostors-Feedback/assets/47288655/a3221c79-0cab-4efd-a1a7-7e3d3a2cb656)

**Comment by Dawie3565** [comment]
same issue found in HDRP 2022.3.22
build test with Barrels and boulders

**Comment by diogovtx** [comment]
Seems like this issue is caused by using the Max Texture Size build option. Is that the case?
If so, IMO, this option shouldn't be used at all. Textures should be resized on individual basis, not globally like this.
![SnippingTool_QJ5AMPHI9C](https://github.com/AmplifyCreations/AmplifyImpostors-Feedback/assets/7001068/356e2b87-1495-4e86-a55e-4bf39cfb1c6f)

Also, make sure all the impostor textures have Max Size on WebGL platform these set properly:
![1 CCOaxtRoAZkWqs3rpSQwBg](https://github.com/AmplifyCreations/AmplifyImpostors-Feedback/assets/7001068/53a97ce8-ee7d-470b-b696-a9eeb573056d)
